// <auto-generated />
using System;
using DevContentEngine.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DevContentEngine.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DevContentEngineDbContext))]
    [Migration("20260812092028_AddImagePromptToGeneratedPost")]
    partial class AddImagePromptToGeneratedPost
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DevContentEngine.Domain.Entities.ContentIdea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ActivityScore")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<string>("ChosenPath")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.PrimitiveCollection<Guid[]>("RelatedActivityIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<Guid?>("RelatedRepositoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RelatedTrendId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RelatedRepositoryId");

                    b.HasIndex("RelatedTrendId");

                    b.ToTable("ContentIdeas", (string)null);
                });

            modelBuilder.Entity("DevContentEngine.Domain.Entities.GeneratedPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Conclusion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ContentIdeaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cta")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Hashtags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Hook")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagePrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("PromptVersionId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("Sources")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContentIdeaId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Hashtags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Hashtags"), "gin");

                    b.HasIndex("PromptVersionId");

                    b.ToTable("GeneratedPosts", (string)null);
                });

            modelBuilder.Entity("DevContentEngine.Domain.Entities.GenerationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChosenPath")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResultingPostId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResultingPostId");

                    b.ToTable("GenerationRuns", (string)null);
                });

            modelBuilder.Entity("DevContentEngine.Domain.Entities.GitHubActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("DetectedTechnologies")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsNoise")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("RepositoryId", "Timestamp");

                    b.ToTable("GitHubActivities", (string)null);
                });

            modelBuilder.Entity("DevContentEngine.Domain.Entities.GitHubRepository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Owner", "Name")
                        .IsUnique();

                    b.ToTable("GitHubRepositories", (string)null);
                });

            modelBuilder.Entity("DevContentEngine.Domain.Entities.PromptVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("PromptVersions", (string)null);
                });

            modelBuilder.Entity("DevContentEngine.Domain.Entities.PublishedPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EngagementNotes")
                        .HasColumnType("text");

                    b.Property<Guid>("GeneratedPostId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedPostId")
                        .IsUnique();

                    b.ToTable("PublishedPosts", (string)null);
                });

            modelBuilder.Entity("DevContentEngine.Domain.Entities.Trend", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("RelevanceScore")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.ToTable("Trends", (string)null);
                });

            modelBuilder.Entity("DevContentEngine.Domain.Entities.ContentIdea", b =>
                {
                    b.HasOne("DevContentEngine.Domain.Entities.GitHubRepository", null)
                        .WithMany()
                        .HasForeignKey("RelatedRepositoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DevContentEngine.Domain.Entities.Trend", null)
                        .WithMany()
                        .HasForeignKey("RelatedTrendId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("DevContentEngine.Domain.Entities.GeneratedPost", b =>
                {
                    b.HasOne("DevContentEngine.Domain.Entities.ContentIdea", null)
                        .WithMany()
                        .HasForeignKey("ContentIdeaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevContentEngine.Domain.Entities.PromptVersion", null)
                        .WithMany()
                        .HasForeignKey("PromptVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DevContentEngine.Domain.Entities.GenerationRun", b =>
                {
                    b.HasOne("DevContentEngine.Domain.Entities.GeneratedPost", null)
                        .WithMany()
                        .HasForeignKey("ResultingPostId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("DevContentEngine.Domain.Entities.GitHubActivity", b =>
                {
                    b.HasOne("DevContentEngine.Domain.Entities.GitHubRepository", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevContentEngine.Domain.Entities.PublishedPost", b =>
                {
                    b.HasOne("DevContentEngine.Domain.Entities.GeneratedPost", null)
                        .WithMany()
                        .HasForeignKey("GeneratedPostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
